export interface InventoryItem {
    ITEM_CODE: string,
    HSN_CODE?: string,
    BAR_CODE?: string,
    ITEM_DESCRIPTION: string,
    UNIT_OF_MEASUREMENT: string,
    ITEM_WEIGHT?: string,
    ITEM_VOLUME?: string,
    ITEM_CATEGORY: string,
    ITEM_CLASSIFICATION: string
};
export interface Warehouse {
    WAREHOUSE_CODE: string,
    WAREHOUSE_NAME: string,
    LOCATION: string,
    COUNTRY: string,
    CITY: string,
    ZONE_: string,
    STREET?: string,
    BULIDING: string,
    POSTAL_CODE: string
};

export interface StockItem {
    ORGANIZATION_CODE: string,
    ORGANIZATION_NAME: string,
    ITEM_CODE: string,
    SERIAL_NUMBER: string,
    LOT_NUMBER: string,
    EXPIRATION_DATE: Date,
    ONHAND_QUANTITY: number
}

export const MOCK_INVENTORY = {
    "OutputParameters": {
        "@xmlns": "http://xmlns.oracle.com/apps/inv/rest/XXMOCI_GET_ITEM_DETAILS_PKG/get_item_details_proc/",
        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "P_RECORD_STATUS": {
            "P_RECORD_STATUS_ITEM": [{
                "ITEM_CODE": "OIL123",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "Woqood Gasoline 95",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "Computers123",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "Dell Latitude T470",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "HEADSET",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "HEADSET",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "ASST.ITHW",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "RICE",
                "HSN_CODE": "112233",
                "BAR_CODE": "12345543",
                "ITEM_DESCRIPTION": "RICE",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "OIL",
                "HSN_CODE": "12321",
                "BAR_CODE": "1122111",
                "ITEM_DESCRIPTION": "OIL",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "RFID",
                "HSN_CODE": "1",
                "BAR_CODE": "1",
                "ITEM_DESCRIPTION": "RFID.OIL",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "SUGAR",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "Sugar",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "STRG.STRG",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "WHEAT",
                "HSN_CODE": "113321",
                "BAR_CODE": "989889",
                "ITEM_DESCRIPTION": "WHEAT",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "RFID",
                "HSN_CODE": "11",
                "BAR_CODE": "11",
                "ITEM_DESCRIPTION": "RICE",
                "UNIT_OF_MEASUREMENT": "BAG",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "TEST",
                "HSN_CODE": "1",
                "BAR_CODE": "1",
                "ITEM_DESCRIPTION": "TEST ASSET",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "MoCI Brochure",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "MoCI Brochure",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "Flour",
                "HSN_CODE": "90321123",
                "BAR_CODE": "987654",
                "ITEM_DESCRIPTION": "Flour",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "HEADSET",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "HEADSET",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "PENS",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "PENS",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "COFFEE",
                "HSN_CODE": "32424",
                "BAR_CODE": "12345",
                "ITEM_DESCRIPTION": "COFFEE",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "CORN",
                "HSN_CODE": "112211",
                "BAR_CODE": "321123",
                "ITEM_DESCRIPTION": "CORN",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "SUGAR",
                "HSN_CODE": null,
                "BAR_CODE": null,
                "ITEM_DESCRIPTION": "Sugar",
                "UNIT_OF_MEASUREMENT": "Each",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "BLACK GRAM",
                "HSN_CODE": "5201",
                "BAR_CODE": "6164000025259",
                "ITEM_DESCRIPTION": "BLACK GRAM",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": "1",
                "ITEM_VOLUME": "1",
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }, {
                "ITEM_CODE": "SI",
                "HSN_CODE": "111122",
                "BAR_CODE": "111111",
                "ITEM_DESCRIPTION": "SI.WHEAT",
                "UNIT_OF_MEASUREMENT": "Kilogram",
                "ITEM_WEIGHT": null,
                "ITEM_VOLUME": null,
                "ITEM_CATEGORY": "CONC.OFSP",
                "ITEM_CLASSIFICATION": "Inventory"
            }]
        }
    }
};